### PR TITLE
Update clear-layer and clear-before feature

### PR DESCRIPTION
**Pull request by ant4x**
This change is [Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/19)

### CODE REVIEW

**Review by ulitiy — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/19)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @ant4x)

___
*[`src/plugin/tune.ts` line 123 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/19#-NN-69cs01bdZQZd8yci:-NN-69cs01bdZQZd8ycj:b-dj6h6e) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/429b7b885ae398608c7ea4721c4d8a0d98b4915a/src/plugin/tune.ts#L123)):*
> ```XML
>   const currentLayerNumber = lesson.children.indexOf(step)
>   const clearLayerNumbers = new Set<number>()
>   lesson.children.forEach((layer, i) => {
> ```

Ты берешь некоторый АККУМУЛЯТОР и его собираешь вдоль некоторого массива. Ровно для этого есть функция .reduce

**Review by ant4x — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/19)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @ulitiy)

___
*[`src/plugin/tune.ts` line 123 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/19#-NN-69cs01bdZQZd8yci:-NN2_28b97B1Y7YXRP-M:b-1hlify) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/429b7b885ae398608c7ea4721c4d8a0d98b4915a/src/plugin/tune.ts#L123)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Ты берешь некоторый АККУМУЛЯТОР и его собираешь вдоль некоторого массива. Ровно для этого есть функция .reduce
</blockquote></details>

Переделал через reduce. Чтобы избежать дубликатов, приходится либо делать аккумулятор Set'ом (как сейчас сделано), либо на выходе делать конструкцию Array.from(new Set(acc)).

**Review by ulitiy — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/19)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @ant4x)

___
*[`src/plugin/tune.ts` line 123 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/19#-NN2mPDu5dodgRrAKzLJ:-NN2mPDu5dodgRrAKzLK:b-m7ukfi) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9e64861c33d65dae5abd7cd886b26e2ba787ede4/src/plugin/tune.ts#L123)):*
> ```XML
>   const currentLayerNumber = lesson.children.indexOf(step)
>   const clearLayerNumbers = lesson.children.reduce((acc, layer, i) => {
>     if (layer.type === 'GROUP' && i <= currentLayerNumber) {
> ```

early return
___
*[`src/plugin/tune.ts` line 126 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/19#-NN2mUnK2TxKleGc2iJ9:-NN2mUnLB35M0s6Sb85I:bz6gjqn) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9e64861c33d65dae5abd7cd886b26e2ba787ede4/src/plugin/tune.ts#L126)):*
> ```XML
>       let clearIdxs = []
>       if (getTags(layer).includes('clear-before')) {
>         clearIdxs.push([...Array(i).keys()].slice(1))
> ```

сразу в аккумулятор и early return, тогда и else не нужен. Зачем эти промежуточные массивы, если ты кладёшь в них только 1 раз? Можно так же через foreach add, можно через new Set([...acc, ...new Set(arr)])

**Review by ulitiy — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/19)* status: all files reviewed, 3 unresolved discussions (waiting on @ant4x)

**Review by ant4x — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/19)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @ulitiy)

___
*[`src/plugin/tune.ts` line 123 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/19#-NN2mPDu5dodgRrAKzLJ:-NN34_uL7mdu1vxey4eW:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9e64861c33d65dae5abd7cd886b26e2ba787ede4/src/plugin/tune.ts#L123)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

early return
</blockquote></details>

Done.
___
*[`src/plugin/tune.ts` line 126 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/19#-NN2mUnK2TxKleGc2iJ9:-NN35s0O0EQDB-vYJqD_:b-riktrm) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9e64861c33d65dae5abd7cd886b26e2ba787ede4/src/plugin/tune.ts#L126)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

сразу в аккумулятор и early return, тогда и else не нужен. Зачем эти промежуточные массивы, если ты кладёшь в них только 1 раз? Можно так же через foreach add, можно через new Set([...acc, ...new Set(arr)])
</blockquote></details>

Переделал с добавлением сразу в аккумулятор.

**Review by ulitiy — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/19)* status: all files reviewed, 1 unresolved discussion (waiting on @ant4x)

*[a discussion](https://reviewable.io/reviews/ulitiy/artworkout-figma/19#-NN3ejSI0pAaHv8W22Mu:-NN3ejSKBqx7Vw_ja7Fl:b-d065z9) (no related file):*
Не работает

___

**Review by ant4x — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/19)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @ulitiy)

*[a discussion](https://reviewable.io/reviews/ulitiy/artworkout-figma/19#-NN3ejSI0pAaHv8W22Mu:-NN8vMrb8yjYUCHqoErz:b5zgfp1) (no related file):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Не работает
</blockquote></details>

Переделал

___

**Review by ulitiy — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/19)* status: all files reviewed, 1 unresolved discussion (waiting on @ant4x)

___
*[`src/plugin/util.ts` line 72 at r5](https://reviewable.io/reviews/ulitiy/artworkout-figma/19#-NNEu-bW5X_ANr53NW50:-NNEu-bW5X_ANr53NW51:b-fknve2) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/caee7dab1ba8ce9ca9e9e85ca0fcd0f757e1760b/src/plugin/util.ts#L72)):*
> ```XML
>   const stepOrderTag = /^o-(\d+)$/
>   return getTags(step)
>     .filter((tag) => tag.match(stepOrderTag))
> ```

.find вместо .filter

тебе же только одно значение нужно. Тогда и индекс не понадобится

**Review by ant4x — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/19)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @ulitiy)

___
*[`src/plugin/util.ts` line 72 at r5](https://reviewable.io/reviews/ulitiy/artworkout-figma/19#-NNEu-bW5X_ANr53NW50:-NNIQ6ci3hzkCJYrnaFK:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/caee7dab1ba8ce9ca9e9e85ca0fcd0f757e1760b/src/plugin/util.ts#L72)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

.find вместо .filter

тебе же только одно значение нужно. Тогда и индекс не понадобится
</blockquote></details>

Done.

**Review by ulitiy — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/19)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ant4x)

**Pull request merged**
