### PR TITLE
Course order list

### PR DESCRIPTION
**Pull request by Ivan-okolzin**
This change is [Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/43)

### CODE REVIEW

**Review by ulitiy — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/43)* status: 0 of 1 approvals obtained, all files reviewed, 4 unresolved discussions (waiting on @Ivan-okolzin)

___
*[`src/app/components/CourseList.tsx` line 18 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/43#-NV0SVnNBH58PZhN3zDH:-NV0SVnNBH58PZhN3zDI:bfhwc5k) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8a9535cf3c3ee46b8b3f6b5fe7b0e4ab9a1f34a7/src/app/components/CourseList.tsx#L18)):*
> ```XML
>     }
> 
>     const newStepsOrder = Array.from(courses)
> ```

ну ты блин хоть названия переменных поправь
___
*[`src/app/components/PublishTab.tsx` line 26 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/43#-NV0U4OX1MgYGBUyvRMe:-NV0U4OX1MgYGBUyvRMf:b-bgv665) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8a9535cf3c3ee46b8b3f6b5fe7b0e4ab9a1f34a7/src/app/components/PublishTab.tsx#L26)):*
> ```XML
>   const [parseCourseList, setParseCourseList] = useState([])
> 
>   const onUpdate = async (selected) => {
> ```

onCourseOrderUpdate конкретно эта переменная
___
*[`src/app/components/PublishTab.tsx` line 44 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/43#-NV0RNQM1y7J8xdKZksu:-NV0RNQM1y7J8xdKZksv:b-bn5sgo) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8a9535cf3c3ee46b8b3f6b5fe7b0e4ab9a1f34a7/src/app/components/PublishTab.tsx#L44)):*
> ```XML
>       })
>       courses.sort((a, b) => a.order - b.order)
>       console.log('courses', courses)
> ```

ненужный лог
___
*[`src/app/components/PublishTab.tsx` line 194 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/43#-NV0RWbY1DG23b_R8Td6:-NV0RWbY1DG23b_R8Td7:bbez3z9) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8a9535cf3c3ee46b8b3f6b5fe7b0e4ab9a1f34a7/src/app/components/PublishTab.tsx#L194)):*
> ```XML
>           <Button
>             disabled={isDisabled}
>             onClick={() => getAllCoursesFromParse()}
> ```

почему на этой кнопке поменялся онклик?

**Review by Ivan-okolzin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/43)* status: 0 of 1 approvals obtained, 0 of 4 files reviewed, 4 unresolved discussions (waiting on @ulitiy)

___
*[`src/app/components/CourseList.tsx` line 18 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/43#-NV0SVnNBH58PZhN3zDH:-NV3cSO2C-3BRYlXWI1o:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8a9535cf3c3ee46b8b3f6b5fe7b0e4ab9a1f34a7/src/app/components/CourseList.tsx#L18)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

ну ты блин хоть названия переменных поправь
</blockquote></details>

Done.
___
*[`src/app/components/PublishTab.tsx` line 26 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/43#-NV0U4OX1MgYGBUyvRMe:-NV3bYyVDrGW7wFZ3_Xi:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8a9535cf3c3ee46b8b3f6b5fe7b0e4ab9a1f34a7/src/app/components/PublishTab.tsx#L26)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

onCourseOrderUpdate конкретно эта переменная
</blockquote></details>

Done.
___
*[`src/app/components/PublishTab.tsx` line 44 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/43#-NV0RNQM1y7J8xdKZksu:-NV3bZWj4xMV7-zYLogR:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8a9535cf3c3ee46b8b3f6b5fe7b0e4ab9a1f34a7/src/app/components/PublishTab.tsx#L44)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

ненужный лог
</blockquote></details>

Done.
___
*[`src/app/components/PublishTab.tsx` line 194 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/43#-NV0RWbY1DG23b_R8Td6:-NV3bZm27Hmh5-MTLRFR:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/8a9535cf3c3ee46b8b3f6b5fe7b0e4ab9a1f34a7/src/app/components/PublishTab.tsx#L194)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

почему на этой кнопке поменялся онклик?
</blockquote></details>

Done.

**Review by ulitiy — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/43)* status: :shipit: complete! 1 of 1 approvals obtained, all files reviewed, all discussions resolved

**Review by ulitiy — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/43)* status: :shipit: complete! 1 of 1 approvals obtained, all files reviewed, all discussions resolved

**Pull request merged**
