### PR TITLE
Implement "Join Steps" feature

### PR DESCRIPTION
**Pull request by ant4x**
This change is [Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/14)

### CODE REVIEW

**Review by ulitiy — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/14)* status: all files reviewed, 3 unresolved discussions (waiting on @ant4x)

___
*[`src/plugin/create.ts` line 337 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/14#-NJv6Mt-712lpNMOMDfw:-NJv6Mt-712lpNMOMDfx:b-7uvqyh) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/e60c7fc1dd60446fa6482b340f5b08f5c75218dd/src/plugin/create.ts#L337)):*
> ```XML
>   }
>   const steps = selection.filter((n) => !isResultStep(n))
>   if (steps.length < 2) {
> ```

объедини оба условия
___
*[`src/plugin/create.ts` line 340 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/14#-NJv5QRCCHeFptzV4lcF:-NJv5QRD1V06d9xjdR8S:bc7q6th) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/e60c7fc1dd60446fa6482b340f5b08f5c75218dd/src/plugin/create.ts#L340)):*
> ```XML
>     return
>   }
>   const leaves = steps.map((n) => findLeafNodes(n as GroupNode)).flat()
> ```

Давай лучше не будем принимать везде этот стандарт уничтожения группировки внутри уроков.

Здесь ничего сложного взять просто все ноды, которые лежат в инпуте.
___
*[`src/plugin/create.ts` line 341 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/14#-NJv67diAmH1EuT7BUm_:-NJv67diAmH1EuT7BUma:b-vmlg05) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/e60c7fc1dd60446fa6482b340f5b08f5c75218dd/src/plugin/create.ts#L341)):*
> ```XML
>   }
>   const leaves = steps.map((n) => findLeafNodes(n as GroupNode)).flat()
>   const firstParentStep = steps[0]
> ```

убирай эту строчку инлайн, не надо настолько подробно, код очевидный

**Review by ant4x — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/14)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @ulitiy)

___
*[`src/plugin/create.ts` line 337 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/14#-NJv6Mt-712lpNMOMDfw:-NJvAIYx2CV4OWMrtOYx:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/e60c7fc1dd60446fa6482b340f5b08f5c75218dd/src/plugin/create.ts#L337)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

объедини оба условия
</blockquote></details>

Done.
___
*[`src/plugin/create.ts` line 340 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/14#-NJv5QRCCHeFptzV4lcF:-NJvSFwN8Ih1erXf5iCr:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/e60c7fc1dd60446fa6482b340f5b08f5c75218dd/src/plugin/create.ts#L340)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Давай лучше не будем принимать везде этот стандарт уничтожения группировки внутри уроков.

Здесь ничего сложного взять просто все ноды, которые лежат в инпуте.
</blockquote></details>

Done.
___
*[`src/plugin/create.ts` line 341 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/14#-NJv67diAmH1EuT7BUm_:-NJvSGFm32NM_xwGVZLA:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/e60c7fc1dd60446fa6482b340f5b08f5c75218dd/src/plugin/create.ts#L341)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

убирай эту строчку инлайн, не надо настолько подробно, код очевидный
</blockquote></details>

Done.

**Review by ulitiy — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/14)* status: all files reviewed, 1 unresolved discussion (waiting on @ant4x)

___
*[`src/plugin/create.ts` line 337 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/14#-NJv6Mt-712lpNMOMDfw:-NJv_Td7D0g7UIDGFASU:brh1su1) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/e60c7fc1dd60446fa6482b340f5b08f5c75218dd/src/plugin/create.ts#L337)):*
<details><summary><i>Previously, ant4x (Anthony Fox) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Неверно, невнимательно

**Review by ant4x — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/14)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @ulitiy)

___
*[`src/plugin/create.ts` line 337 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/14#-NJv6Mt-712lpNMOMDfw:-NJvdFdN-h4OX6lXaY9L:b-s9j4o0) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/e60c7fc1dd60446fa6482b340f5b08f5c75218dd/src/plugin/create.ts#L337)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Неверно, невнимательно
</blockquote></details>

Поправил

**Review by ulitiy — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ant4x)

**Pull request merged**
