### PR TITLE
New format tab

### PR DESCRIPTION
**Pull request by Ivan-okolzin**
This change is [Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/22)

### CODE REVIEW

**Review by ulitiy — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/22)* status: 0 of 1 approvals obtained, all files reviewed, 13 unresolved discussions (waiting on @Ivan-okolzin)

___
*[`package.json` line 60 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOBxujaDrnMZseY13vE:-NOBxujaDrnMZseY13vF:b573x5q) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/package.json#L60)):*
> ```JSON
>     "ws": "^7.4.5"
>   },
>   "dependencies": {
> ```

перемести в devDependencies
___
*[`src/app/components/FormatTab.css` line 28 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOC-GnJ9Ls_iqpSjUse:-NOC-GnJ9Ls_iqpSjUsf:b-exo6tr) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/app/components/FormatTab.css#L28)):*
> ```CSS
>     align-content: center;
>     justify-content: center;
> }
> ```

prettify везде должно быть
___
*[`src/app/components/FormatTab.tsx` line 28 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOCBQit6fnnrkwf6RBg:-NOCBQit6fnnrkwf6RBh:b-bu310t) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/app/components/FormatTab.tsx#L28)):*
> ```XML
> 
>   function selectError(errorIndex?: number) {
>     console.log('selectError', errorIndex)
> ```

остатки дебага
___
*[`src/app/components/FormatTab.tsx` line 29 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOCBknpBGJEQTVGjMYh:-NOCBknq0PzDjJtOFYMd:b-a66xav) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/app/components/FormatTab.tsx#L29)):*
> ```XML
>   function selectError(errorIndex?: number) {
>     console.log('selectError', errorIndex)
>     errorIndex ? pluginApi.selectError(errorIndex) : pluginApi.selectError(getLineNumber()- 1)
> ```

эта логика вроде не нужна, если мы отказываемся от текстовых ошибок?
___
*[`src/app/components/FormatTab.tsx` line 102 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOC6Fat09BDu8qrjG-Z:-NOC6Fat09BDu8qrjG-_:b-jvyoy7) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/app/components/FormatTab.tsx#L102)):*
> ```XML
> 
> 
>   function renderLine(line: errorsForPrint, index: number) {
> ```

renderRow(row
___
*[`src/plugin/index.ts` line 12 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOCB3SQ7CvgrWfehrFd:-NOCB3SQ7CvgrWfehrFe:bem312k) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/plugin/index.ts#L12)):*
> ```XML
> figma.ui.resize(340, 450)
> console.clear()
> ```

Зачем здесь везде rpc? Ты из плагина вызываешь плагин.
___
*[`src/plugin/linter.ts` line 16 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOC2iJ56HvNBYoB5vHu:-NOC2iJ56HvNBYoB5vHv:b-ghb6zm) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/plugin/linter.ts#L16)):*
> ```XML
>   pageName?: string
>   nodeName?: string
>   nodeType?: string
> ```

а в стрипнутой версии нод нет этой инфы? По возможности, надо избавиться от избыточного интерфейса, м.б. объединить с предыдущим.
___
*[`src/plugin/linter.ts` line 22 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOC1yn1CMMTBEZlxS9_:-NOC1yn1CMMTBEZlxS9a:bz79xzc) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/plugin/linter.ts#L22)):*
> ```XML
> }
> 
> let errors: LintError[] = []
> ```

не осталось причин для глобальной переменной
___
*[`src/plugin/linter.ts` line 37 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOC3YUH3otGTW5VPH70:-NOC3YUH3otGTW5VPH71:b-3gpdnb) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/plugin/linter.ts#L37)):*
> ```XML
>   '#ff9900',
>   '#00ff00',
> }
> ```

Зачем "серверу" об этом знать?
___
*[`src/plugin/linter.ts` line 51 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOC2IBr3WrUu-53h3Ev:-NOC2IBr3WrUu-53h3Ew:b5y5gwm) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/plugin/linter.ts#L51)):*
> ```XML
> 
> export async function printErrors() {
>   figma.ui.resize(750, 400)
> ```

получится ли без увеличения окна?
___
*[`src/plugin/linter.ts` line 87 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOC1X7z6mv_6OwO2R_P:-NOC1X7z6mv_6OwO2R_Q:b9aga6o) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/plugin/linter.ts#L87)):*
> ```XML
>   return {
>     tableErrors: sortedErrors ,
>     textErrors: text,
> ```

зачем нам text? Убирай, возвращай просто массив ошибок.
___
*[`src/plugin/linter.ts` line 608 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOC1Ejd7fdtSYUBDKIV:-NOC1Ejd7fdtSYUBDKIW:b-tqd6qi) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/plugin/linter.ts#L608)):*
> ```XML
> }
> 
> export function onLintCourse() {
> ```

эти функции не нужны, lintCourse должен возвращать ошибки напрямую
___
*[`src/plugin/tune.ts` line 155 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOC-qxW-O4Oc0wmTurl:-NOC-qxW-O4Oc0wmTurm:b-bu310t) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/plugin/tune.ts#L155)):*
> ```XML
>   lastMode = settings.displayMode
>   const { displayMode, stepNumber } = settings
>   console.log('page', page)
> ```

остатки дебага

**Comment by Ivan-okolzin** [comment]
*[`src/plugin/linter.ts` line 51 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOC2IBr3WrUu-53h3Ev:-NODk_ThB3BJuOWIvJU9:b8arv7h) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/plugin/linter.ts#L51)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

получится ли без увеличения окна?
</blockquote></details>

Можно сделать сразу большой вариант плагина без увеличения его при нажатии. Дела как было до этого.

**Comment by Ivan-okolzin** [comment]
*[`src/plugin/linter.ts` line 22 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOC1yn1CMMTBEZlxS9_:-NOE7OGDAv5w6kDYmUP8:bg5ssdd) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/plugin/linter.ts#L22)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

не осталось причин для глобальной переменной
</blockquote></details>

Почему? Мне же нужен массив, куда я буду сохранять ошибки через assert.

**Review by ulitiy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/22)* status: 0 of 1 approvals obtained, all files reviewed, 13 unresolved discussions (waiting on @Ivan-okolzin)

___
*[`src/plugin/linter.ts` line 22 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOC1yn1CMMTBEZlxS9_:-NOI7da4EB17f83B6nY9:bs7mr0i) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/plugin/linter.ts#L22)):*
<details><summary><i>Previously, Ivan-okolzin wrote…</i></summary><blockquote>

Почему? Мне же нужен массив, куда я буду сохранять ошибки через assert.  
</blockquote></details>

Ты вызываешь функцию, сразу возвращающую клиенту ошибки. Клиент хранит ошибки в стейте. Зачем эта переменная?
___
*[`src/plugin/linter.ts` line 51 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOC2IBr3WrUu-53h3Ev:-NOI9-Fi1XYgELGhmp5x:b-j3qqtv) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/plugin/linter.ts#L51)):*
<details><summary><i>Previously, Ivan-okolzin wrote…</i></summary><blockquote>

Можно сделать сразу большой вариант плагина без увеличения его при нажатии. Дела как было до этого. 
</blockquote></details>

Хорошая тема добавить кнопку minimize/maximize

**Review by Ivan-okolzin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/22)* status: 0 of 1 approvals obtained, 0 of 14 files reviewed, 12 unresolved discussions (waiting on @ulitiy)

___
*[`package.json` line 60 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOBxujaDrnMZseY13vE:-NODifwU-CZV6ZI-HCLr:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/package.json#L60)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

перемести в devDependencies
</blockquote></details>

Done.
___
*[`src/app/components/FormatTab.css` line 28 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOC-GnJ9Ls_iqpSjUse:-NODigWKCOVCs0vjN6le:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/app/components/FormatTab.css#L28)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

prettify везде должно быть
</blockquote></details>

Done.
___
*[`src/app/components/FormatTab.tsx` line 28 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOCBQit6fnnrkwf6RBg:-NODinEJC_MTjdu0Hi6o:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/app/components/FormatTab.tsx#L28)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

остатки дебага
</blockquote></details>

Done.
___
*[`src/app/components/FormatTab.tsx` line 29 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOCBknpBGJEQTVGjMYh:-NODinTh2ghP6iNmjF8X:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/app/components/FormatTab.tsx#L29)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

эта логика вроде не нужна, если мы отказываемся от текстовых ошибок?
</blockquote></details>

Done.
___
*[`src/app/components/FormatTab.tsx` line 102 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOC6Fat09BDu8qrjG-Z:-NODioNW9xlxjgSv36zY:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/app/components/FormatTab.tsx#L102)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

renderRow(row
</blockquote></details>

Done.
___
*[`src/plugin/index.ts` line 12 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOCB3SQ7CvgrWfehrFd:-NODipEwCtHJBwwvxT9U:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/plugin/index.ts#L12)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Зачем здесь везде rpc? Ты из плагина вызываешь плагин.
</blockquote></details>

Done.
___
*[`src/plugin/linter.ts` line 16 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOC2iJ56HvNBYoB5vHu:-NOEiMo08uBQDpUUj7m6:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/plugin/linter.ts#L16)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

а в стрипнутой версии нод нет этой инфы? По возможности, надо избавиться от избыточного интерфейса, м.б. объединить с предыдущим.
</blockquote></details>

Done.
___
*[`src/plugin/linter.ts` line 22 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOC1yn1CMMTBEZlxS9_:-NOIyuIj9-Xe7QYnVDFB:bbfh73p) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/plugin/linter.ts#L22)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Ты вызываешь функцию, сразу возвращающую клиенту ошибки. Клиент хранит ошибки в стейте. Зачем эта переменная?
</blockquote></details>

Я вызываю функцию lintPage и lintCourse, которая пробегает по всем элементам, линтит их и собирает все в массив errors в linter.ts,
когда я все собрал, я передаю отсортированный массив в плагин и сохраняю его в стейте (Чтобы за раз дернуть все данные и перерендерить интерфейс). Ты хочешь, чтобы у меня assert возвращал ошибку сразу в стейт плагина или мне через все функции тащить массив ошибок аргументом, а потом возвращать его плагину? 
___
*[`src/plugin/linter.ts` line 37 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOC3YUH3otGTW5VPH70:-NOEiNh-7VwuW-j6G9Fq:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/plugin/linter.ts#L37)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Зачем "серверу" об этом знать?
</blockquote></details>

Done.
___
*[`src/plugin/linter.ts` line 51 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOC2IBr3WrUu-53h3Ev:-NOIv7zL3XxNNTeid2Se:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/plugin/linter.ts#L51)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Хорошая тема добавить кнопку minimize/maximize
</blockquote></details>

Done.
___
*[`src/plugin/linter.ts` line 87 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOC1X7z6mv_6OwO2R_P:-NOEiOZuAqyG3TprK_lV:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/plugin/linter.ts#L87)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

зачем нам text? Убирай, возвращай просто массив ошибок.
</blockquote></details>

Done.
___
*[`src/plugin/linter.ts` line 608 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOC1Ejd7fdtSYUBDKIV:-NOEmFOz2p99VPP0O45Y:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/plugin/linter.ts#L608)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

эти функции не нужны, lintCourse должен возвращать ошибки напрямую
</blockquote></details>

Done.
___
*[`src/plugin/tune.ts` line 155 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOC-qxW-O4Oc0wmTurl:-NODo3QEBrGWvj__5j0g:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/9903f6a86fe1ff815edc6de124368e6d19a7499b/src/plugin/tune.ts#L155)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

остатки дебага
</blockquote></details>

Done.

**Review by ulitiy — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/22)* status: 0 of 1 approvals obtained, all files reviewed, 1 unresolved discussion (waiting on @Ivan-okolzin)

___
*[`src/plugin/linter.ts` line 499 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOSF3EIChdqft5-clvf:-NOSF3EIChdqft5-clvg:bbt69ej) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/58171c901230c42d384021e854f5e6edebe2cdc7/src/plugin/linter.ts#L499)):*
> ```XML
> }
> 
> export function lintPage(currentPage?: PageNode | null, isCourseLinting?: boolean) {
> ```

давай назовём переменную appendErrors, чтобы было понятно, что именно она делает

**Review by ulitiy — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/22)* status: 0 of 1 approvals obtained, all files reviewed, 1 unresolved discussion (waiting on @Ivan-okolzin)

___
*[`src/plugin/linter.ts` line 499 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOSF3EIChdqft5-clvf:-NOWEzeu5aP3SWFuG3Ys:b-nk013f) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/58171c901230c42d384021e854f5e6edebe2cdc7/src/plugin/linter.ts#L499)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

давай назовём переменную appendErrors, чтобы было понятно, что именно она делает
</blockquote></details>

isCourseLinting -> appendErrors :roll_eyes: 
А остальное верни наоборот

**Review by ulitiy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/22)* status: 0 of 1 approvals obtained, all files reviewed, 1 unresolved discussion (waiting on @Ivan-okolzin)

___
*[`src/plugin/linter.ts` line 499 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/22#-NOSF3EIChdqft5-clvf:-NOWFEFoBBibwZbUt45t:b40jb34) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/58171c901230c42d384021e854f5e6edebe2cdc7/src/plugin/linter.ts#L499)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

isCourseLinting -> appendErrors :roll_eyes: 
А остальное верни наоборот
</blockquote></details>

isCourseLinting же по сути означает "добавлять ошибки в массив (вместо замены массива)"

**Review by ulitiy — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/22)* status: :shipit: complete! 1 of 1 approvals obtained, all files reviewed, all discussions resolved

**Review by ulitiy — APPROVED** [review]
> Reviewed 8 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/22)* status: :shipit: complete! 1 of 1 approvals obtained, all files reviewed, all discussions resolved

**Review by ulitiy — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/22)* status: :shipit: complete! 1 of 1 approvals obtained, all files reviewed, all discussions resolved

**Pull request merged**
