### PR TITLE
Set tags on leaf nodes and steps

### PR DESCRIPTION
**Pull request by ant4x**
This change is [Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/11)

### CODE REVIEW

**Review by ulitiy — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/11)* status: all files reviewed, 5 unresolved discussions (waiting on @ant4x)

___
*[`src/plugin/create.ts` line 147 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/11#-NJRmR79EmQUMIHy7FgW:-NJRmR79EmQUMIHy7FgX:b-9542o2) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/0c436de303dc5af6275fcbf6955f723092e285de/src/plugin/create.ts#L147)):*
> ```XML
> 
> function nameLeafNodes(nodes: readonly SceneNode[]) {
>   let allStrokes: boolean = true
> ```

array.find вместо вот этих 6 строк
___
*[`src/plugin/create.ts` line 159 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/11#-NJRn-fvBoktKPfK8VCo:-NJRn-fvBoktKPfK8VCp:bo4z9fu) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/0c436de303dc5af6275fcbf6955f723092e285de/src/plugin/create.ts#L159)):*
> ```XML
> }
> 
> function nameStepNodes(step: GroupNode) {
> ```

ты один степ переименуешь, а не множество, исправь название функции
___
*[`src/plugin/create.ts` line 165 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/11#-NJRnPXtANxdElq8CS3j:-NJRnPXtANxdElq8CS3k:b6uss4t) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/0c436de303dc5af6275fcbf6955f723092e285de/src/plugin/create.ts#L165)):*
> ```XML
>   )
>   let strokes = leafs.filter((n) => 'strokes' in n && n.strokes.length > 0)
>   let multistepType = fills.length >= strokes.length ? 'bg' : 'brush'
> ```

не, тут если fills в принципе есть, то bg, иначе brush
___
*[`src/plugin/create.ts` line 166 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/11#-NJRo-tV8_CrknwYbEs_:-NJRo-tV8_CrknwYbEsa:b-43jmb6) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/0c436de303dc5af6275fcbf6955f723092e285de/src/plugin/create.ts#L166)):*
> ```XML
>   let strokes = leafs.filter((n) => 'strokes' in n && n.strokes.length > 0)
>   let multistepType = fills.length >= strokes.length ? 'bg' : 'brush'
>   let maxWeight: number = 1
> ```

.map чтобы извлечь weight (или ноль), потом Math.max(...arr)

больше пользуйся замыканиями и стандартными инструментами
___
*[`src/plugin/create.ts` line 197 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/11#-NJRpHroDQEIlKO3o4rc:-NJRpHroDQEIlKO3o4rd:b-6sjl7) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/0c436de303dc5af6275fcbf6955f723092e285de/src/plugin/create.ts#L197)):*
> ```XML
>   const frame = parentStep.parent
>   const index = frame.children.findIndex((n: SceneNode) => n === parentStep)
>   createStepNode(frame, nodes, index)
> ```

а здесь почему нет append?

**Review by ant4x — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/11)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @ulitiy)

___
*[`src/plugin/create.ts` line 147 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/11#-NJRmR79EmQUMIHy7FgW:-NJS9538EKyHgCONQON3:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/0c436de303dc5af6275fcbf6955f723092e285de/src/plugin/create.ts#L147)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

array.find вместо вот этих 6 строк
</blockquote></details>

Done.
___
*[`src/plugin/create.ts` line 159 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/11#-NJRn-fvBoktKPfK8VCo:-NJSCVtZ517nehSXahx9:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/0c436de303dc5af6275fcbf6955f723092e285de/src/plugin/create.ts#L159)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

ты один степ переименуешь, а не множество, исправь название функции
</blockquote></details>

Done.
___
*[`src/plugin/create.ts` line 165 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/11#-NJRnPXtANxdElq8CS3j:-NJSDVgy-mOP5xJuOM5O:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/0c436de303dc5af6275fcbf6955f723092e285de/src/plugin/create.ts#L165)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

не, тут если fills в принципе есть, то bg, иначе brush
</blockquote></details>

Done.
___
*[`src/plugin/create.ts` line 166 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/11#-NJRo-tV8_CrknwYbEs_:-NJSLT4T7gJM0pWOfOZJ:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/0c436de303dc5af6275fcbf6955f723092e285de/src/plugin/create.ts#L166)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

.map чтобы извлечь weight (или ноль), потом Math.max(...arr)

больше пользуйся замыканиями и стандартными инструментами
</blockquote></details>

Done.
___
*[`src/plugin/create.ts` line 197 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/11#-NJRpHroDQEIlKO3o4rc:-NJSGZvdAk091msyLHQF:bbtx9qr) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/0c436de303dc5af6275fcbf6955f723092e285de/src/plugin/create.ts#L197)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

а здесь почему нет append?
</blockquote></details>

Я в separateStep ничего пока не менял, только рефакторил. Но append судя по всему и в splitByColor не нужен, т.к. группировка уже всё делает. Исправил.

**Review by ulitiy — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/11)* status: all files reviewed, 2 unresolved discussions (waiting on @ant4x)

___
*[`src/plugin/create.ts` line 151 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/11#-NJSkpyd1DAkcpMUBKDm:-NJSkpyd1DAkcpMUBKDn:b-bg68sm) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/de0bf41c3abe20769d2a760e7218e096e6e96695/src/plugin/create.ts#L151)):*
> ```XML
>       (node) =>
>         'fills' in node && node.fills !== figma.mixed && node.fills.length > 0
>     ) === undefined
> ```

!nodes...

не надо писать === undefined

Не могу сказать что это более правильно, это просто я использую такой стиль.
___
*[`src/plugin/create.ts` line 165 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/11#-NJSlTkg1gTxPjaPy_Oj:-NJSlTkg1gTxPjaPy_Ok:bqrx198) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/de0bf41c3abe20769d2a760e7218e096e6e96695/src/plugin/create.ts#L165)):*
> ```XML
>   let strokes = leafs.filter((n) => 'strokes' in n && n.strokes.length > 0)
>   let multistepType = fills.length > 0 ? 'bg' : 'brush'
>   let strokeWeightsArr: number[] = strokes.map((node) => {
> ```

Зачем здесь явное описание типа? Ты условие ненужное написал, при этом ты нарушишь этот тип, если у тебя будет false в условии, т.к. вернется undefined.

node['strokeWeight'] || 0 , одной строчкой

**Review by ant4x — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/11)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @ulitiy)

___
*[`src/plugin/create.ts` line 151 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/11#-NJSkpyd1DAkcpMUBKDm:-NJUos8X4MTjebFXJWwL:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/de0bf41c3abe20769d2a760e7218e096e6e96695/src/plugin/create.ts#L151)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

!nodes...

не надо писать === undefined

Не могу сказать что это более правильно, это просто я использую такой стиль.
</blockquote></details>

Done.
___
*[`src/plugin/create.ts` line 165 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/11#-NJSlTkg1gTxPjaPy_Oj:-NJUoqDm2WLJNxjCa2JA:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/de0bf41c3abe20769d2a760e7218e096e6e96695/src/plugin/create.ts#L165)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Зачем здесь явное описание типа? Ты условие ненужное написал, при этом ты нарушишь этот тип, если у тебя будет false в условии, т.к. вернется undefined.

node['strokeWeight'] || 0 , одной строчкой
</blockquote></details>

Done.

**Review by ulitiy — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/11)* status: all files reviewed, 2 unresolved discussions (waiting on @ant4x)

___
*[`src/plugin/create.ts` line 188 at r3](https://reviewable.io/reviews/ulitiy/artworkout-figma/11#-NJWHQb0-nolcIoSqaY3:-NJWHQb0-nolcIoSqaY4:byam2ga) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/1aeed0b3f69d84ee4f23498f7cc2e82c521cbdf0/src/plugin/create.ts#L188)):*
> ```XML
>   const nodes: readonly SceneNode[] = figma.currentPage.selection
>   const parentStep = findParent(nodes[0], (n) => n.name.startsWith('step'))
>   if (!parentStep || parentStep.name === 'step s-multistep-result') {
> ```

getTags
___
*[`src/plugin/create.ts` line 208 at r3](https://reviewable.io/reviews/ulitiy/artworkout-figma/11#-NJWHCRU4GRexpN3PNPd:-NJWHCRU4GRexpN3PNPe:b-oyvlq4) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/1aeed0b3f69d84ee4f23498f7cc2e82c521cbdf0/src/plugin/create.ts#L208)):*
> ```XML
>   ) as FrameNode
>   const firstStep = lesson.children.find(
>     (el) => el.name.startsWith('step') && el.name !== 'step s-multistep-result'
> ```

используй `getTags().includes('s-multistep-result')`, пожалуйста, везде в таких случаях, уже проходили. Во-первых, унификация, во-вторых, порядок тегов неважен, мало ли как там перемешается.

**Review by ant4x — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/11)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @ulitiy)

___
*[`src/plugin/create.ts` line 188 at r3](https://reviewable.io/reviews/ulitiy/artworkout-figma/11#-NJWHQb0-nolcIoSqaY3:-NJalo9n5CCDZmzhcXP5:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/1aeed0b3f69d84ee4f23498f7cc2e82c521cbdf0/src/plugin/create.ts#L188)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

getTags
</blockquote></details>

Done.
___
*[`src/plugin/create.ts` line 208 at r3](https://reviewable.io/reviews/ulitiy/artworkout-figma/11#-NJWHCRU4GRexpN3PNPd:-NJamBi_BO-S_tqWZxEY:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/1aeed0b3f69d84ee4f23498f7cc2e82c521cbdf0/src/plugin/create.ts#L208)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

используй `getTags().includes('s-multistep-result')`, пожалуйста, везде в таких случаях, уже проходили. Во-первых, унификация, во-вторых, порядок тегов неважен, мало ли как там перемешается.
</blockquote></details>

Done.

**Review by ulitiy — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/11)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ant4x)

**Pull request merged**
