### PR TITLE
template group showing in T mode

### PR DESCRIPTION
**Pull request by Ivan-okolzin**
This change is [Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/39)

### CODE REVIEW

**Review by ulitiy — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/39)* status: 0 of 1 approvals obtained, all files reviewed, 3 unresolved discussions (waiting on @Ivan-okolzin)

___
*[`src/plugin/tune.ts` line 35 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/39#-NSpyeWrC5N-8iyHLN6Z:-NSpyeWrC5N-8iyHLN6_:b83eolm) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/6d751df14c3750d6c6c27c7eb792c2dda54a4bca/src/plugin/tune.ts#L35)):*
> ```XML
>     .forEach((el) => el.remove())
>   //show template groups
>   figma.currentPage
> ```

не думаю, что этому место в deleteTmp()
tmp здесь temporary (как обычно), а не template.
___
*[`src/plugin/tune.ts` line 101 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/39#-NSpzNA39mE_igiPaWim:-NSpzNA39mE_igiPaWin:bv5x5ac) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/6d751df14c3750d6c6c27c7eb792c2dda54a4bca/src/plugin/tune.ts#L101)):*
> ```XML
>       }
>     })
>   const templateGroup = step.findChild((g) => g.name == 'template')
> ```

А зачем его копировать? Его надо просто показать (или не прятать).
М.б. автор хочет внести изменения в темплейт, а клон просто удалится при переключении режима.
___
*[`src/plugin/tune.ts` line 262 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/39#-NSpzZVl48RUO2XEG2zV:-NSpzZVl48RUO2XEG2zW:bor44j9) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/6d751df14c3750d6c6c27c7eb792c2dda54a4bca/src/plugin/tune.ts#L262)):*
> ```XML
>         step.children.forEach(() => {
>           const groupTemplate = step.findChild((g) => g.name == 'template')
>           if (groupTemplate) {
> ```

Почему не findChild? Надо стараться писать унифицированный код.

**Review by ulitiy — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/39)* status: 0 of 1 approvals obtained, all files reviewed, 2 unresolved discussions (waiting on @Ivan-okolzin)

___
*[`src/plugin/tune.ts` line 115 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/39#-NTWg_NKDusxw7o-q1QK:-NTWg_NKDusxw7o-q1QL:b-3l6m20) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/1f028956d23f1610a6a0ed0fd81d9737ae582314/src/plugin/tune.ts#L115)):*
> ```XML
> 
>   template
>     .findAll((el) => !getTags(el).includes('rgb-template'))
> ```

на этом этапе их можно просто удалить и всё, не погружаясь внутри, не играя с видимостью, нет?
___
*[`src/plugin/tune.ts` line 122 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/39#-NTWgmXgAHPZKc1EVbHL:-NTWgmXgAHPZKc1EVbHM:bdvohin) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/1f028956d23f1610a6a0ed0fd81d9737ae582314/src/plugin/tune.ts#L122)):*
> ```XML
>       el.visible = false
>     })
>   const templateGroup = step.findChild((g) => g.name.includes('template'))
> ```

используй getTags. Иначе у тебя сюда например и rgb-template тоже попадают, например.

**Comment by Ivan-okolzin** [comment]
*[`src/plugin/tune.ts` line 115 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/39#-NTWg_NKDusxw7o-q1QK:-NTXd0Z689vbJgb7xB9b:b-swj2n1) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/1f028956d23f1610a6a0ed0fd81d9737ae582314/src/plugin/tune.ts#L115)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

на этом этапе их можно просто удалить и всё, не погружаясь внутри, не играя с видимостью, нет?
</blockquote></details>

При удалении он мне выдает The node with id "1943:1519" does not exist. Поэтому я просто скрываю тут их.

**Review by Ivan-okolzin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/39)* status: 0 of 1 approvals obtained, all files reviewed, 2 unresolved discussions (waiting on @ulitiy)

___
*[`src/plugin/tune.ts` line 122 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/39#-NTWgmXgAHPZKc1EVbHL:-NTXev9n0iu0i2W5VGOf:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/1f028956d23f1610a6a0ed0fd81d9737ae582314/src/plugin/tune.ts#L122)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

используй getTags. Иначе у тебя сюда например и rgb-template тоже попадают, например.
</blockquote></details>

Done.

**Review by ulitiy — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/39)* status: 0 of 1 approvals obtained, all files reviewed, 1 unresolved discussion (waiting on @Ivan-okolzin)

___
*[`src/plugin/tune.ts` line 115 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/39#-NTWg_NKDusxw7o-q1QK:-NTavZbE1wQnrCmrLGYH:b-yszhg1) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/1f028956d23f1610a6a0ed0fd81d9737ae582314/src/plugin/tune.ts#L115)):*
<details><summary><i>Previously, Ivan-okolzin wrote…</i></summary><blockquote>

При удалении он мне выдает The node with id "1943:1519" does not exist. Поэтому я просто скрываю тут их. 
</blockquote></details>

Это не решение. Ну скрой целиком все rgbt хотя бы, зачем скрывать листья? Я вообще не понимаю эту многоэтажную логику, зачем она?

**Review by Ivan-okolzin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/39)* status: 0 of 1 approvals obtained, 1 of 5 files reviewed, 1 unresolved discussion (waiting on @ulitiy)

___
*[`src/plugin/tune.ts` line 115 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/39#-NTWg_NKDusxw7o-q1QK:-NTmkPAq2-Azk_I7ImTr:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/1f028956d23f1610a6a0ed0fd81d9737ae582314/src/plugin/tune.ts#L115)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Это не решение. Ну скрой целиком все rgbt хотя бы, зачем скрывать листья? Я вообще не понимаю эту многоэтажную логику, зачем она?
</blockquote></details>

Done.

**Review by ulitiy — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/39)* status: 0 of 1 approvals obtained, 4 of 5 files reviewed, 1 unresolved discussion (waiting on @Ivan-okolzin)

___
*[`src/plugin/tune.ts` line 115 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/39#-NTWg_NKDusxw7o-q1QK:-NUA-gwp7De1lZ7aRqM1:behmd9a) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/1f028956d23f1610a6a0ed0fd81d9737ae582314/src/plugin/tune.ts#L115)):*
<details><summary><i>Previously, Ivan-okolzin wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Я ошибся, а ты бездумно следуешь указаниям, меня не устраивает такая работа.
Твой предыдущий код нерабочий, и текущий тоже нерабочий.

Пример, почему предыдущий нерабочий: есть группа RGBT, в которой листья. У тебя в массив вошли эти листья, ты их скрыл, хотя они должны были быть показаны.

Как правильно делать: например, скрыть все листья, а потом показать те листья, которые лежат внутри RGBT или сами являются RGBT.

**Comment by Ivan-okolzin** [comment]
*[`src/plugin/tune.ts` line 115 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/39#-NTWg_NKDusxw7o-q1QK:-NUMH6p7EDz4ngxycC1g:by3hlg) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/1f028956d23f1610a6a0ed0fd81d9737ae582314/src/plugin/tune.ts#L115)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Я ошибся, а ты бездумно следуешь указаниям, меня не устраивает такая работа.
Твой предыдущий код нерабочий, и текущий тоже нерабочий.

Пример, почему предыдущий нерабочий: есть группа RGBT, в которой листья. У тебя в массив вошли эти листья, ты их скрыл, хотя они должны были быть показаны.

Как правильно делать: например, скрыть все листья, а потом показать те листья, которые лежат внутри RGBT или сами являются RGBT.
</blockquote></details>

Сделал рекурсивной функцией, которой до этого скрывал элементы в режиме P.

**Review by ulitiy — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/39)* status: :shipit: complete! 1 of 1 approvals obtained, all files reviewed, all discussions resolved

___
*[`src/plugin/tune.ts` line 115 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/39#-NTWg_NKDusxw7o-q1QK:-NUZg0GM2wNmNyYRZbiA:b-dzili6) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/1f028956d23f1610a6a0ed0fd81d9737ae582314/src/plugin/tune.ts#L115)):*
<details><summary><i>Previously, Ivan-okolzin wrote…</i></summary><blockquote>

Сделал рекурсивной функцией, которой до этого скрывал элементы в режиме P. 
</blockquote></details>

Отлично

**Review by ulitiy — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/39)* status: :shipit: complete! 1 of 1 approvals obtained, all files reviewed, all discussions resolved

**Pull request merged**
