### PR TITLE
next brush step logic and button

### PR DESCRIPTION
**Pull request by Ivan-okolzin**
This change is [Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/31)

### CODE REVIEW

**Review by ulitiy — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/31)* status: 0 of 1 approvals obtained, 8 of 10 files reviewed, 7 unresolved discussions (waiting on @Ivan-okolzin)

___
*[`src/plugin/tune.ts` line 175 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NRE0GHp4RQDD8XsHA7x:-NRE0GHp4RQDD8XsHA7y:bwoa7zs) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/b279186b71b051743130b2892be2493e9e050870/src/plugin/tune.ts#L175)):*
> ```XML
>       if(!lesson) return
>       lesson
>         .findAll((el) => el.name.startsWith('tmp-'))
> ```

Допиши функцию deleteTmp, устрани дублирование кода
___
*[`src/plugin/tune.ts` line 201 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NRDyK_3233C7Ws92VhX:-NRDyK_3233C7Ws92VhY:b-8020ws) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/b279186b71b051743130b2892be2493e9e050870/src/plugin/tune.ts#L201)):*
> ```XML
> 
>   if(settings.nextBrushStep){
>     const steps = stepsByOrder(lesson)
> ```

Сделай пожалуйста функцию selectNextStep(criteria: bool). Зачем это прикручивать в updateDisplay?
___
*[`src/plugin/tune.ts` line 202 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NRDwn5x1JYlMf9gNZgd:-NRDwn5x1JYlMf9gNZge:b-go7ud5) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/b279186b71b051743130b2892be2493e9e050870/src/plugin/tune.ts#L202)):*
> ```XML
>   if(settings.nextBrushStep){
>     const steps = stepsByOrder(lesson)
>     const nextStep = steps.find((step, index) => getTags(step).includes('s-multistep-brush') && index > (stepNumber - 1))
> ```

arr.slice.find
___
*[`src/plugin/tune.ts` line 205 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NRDxNpOBWuKSOZ0JWN1:-NRDxNpOBWuKSOZ0JWN2:bf8ebft) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/b279186b71b051743130b2892be2493e9e050870/src/plugin/tune.ts#L205)):*
> ```XML
> 
>       if (!nextStep) {
>         const lessons = figma.root.children as unknown as FrameNode[]
> ```

это же PageNode?
___
*[`src/plugin/tune.ts` line 207 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NRDxc4G6tVs-CG3I42D:-NRDxc4G6tVs-CG3I42E:b-7je4b7) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/b279186b71b051743130b2892be2493e9e050870/src/plugin/tune.ts#L207)):*
> ```XML
>         const lessons = figma.root.children as unknown as FrameNode[]
>           const nextLesson = lessons.find((newLesson, index) => {
>             if (index > lessons.indexOf(lesson.parent as FrameNode)) {
> ```

slice
___
*[`src/plugin/tune.ts` line 209 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NRDy06X1W6nXavOd9ew:-NRDy06YCIwAl4BjJd82:b-m7ukfi) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/b279186b71b051743130b2892be2493e9e050870/src/plugin/tune.ts#L209)):*
> ```XML
>             if (index > lessons.indexOf(lesson.parent as FrameNode)) {
>               const lessonFrame = newLesson.children.find((t) => t.name == 'lesson') as FrameNode
>               if (lessonFrame) {
> ```

early return
___
*[`src/plugin/tune.ts` line 404 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NRDz_Uo87D4jPTnnhhD:-NRDz_Uo87D4jPTnnhhE:b-1s2v26) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/b279186b71b051743130b2892be2493e9e050870/src/plugin/tune.ts#L404)):*
> ```XML
>     const lesson = getCurrentLesson()
>     if (!selection || !lesson || !lesson.children.includes(selection)) {
>       updateDisplay(figma.currentPage, { displayMode: lastMode, stepNumber: 1, nextBrushStep: false })
> ```

Эти все изменения не нужны, если ты вынешь эту логику из updateDisplay.

**Comment by Ivan-okolzin** [comment]
*[`src/plugin/tune.ts` line 404 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NRDz_Uo87D4jPTnnhhD:-NRI7R0H1xhSyyQ7nmJl:b-19z1e) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/b279186b71b051743130b2892be2493e9e050870/src/plugin/tune.ts#L404)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Эти все изменения не нужны, если ты вынешь эту логику из updateDisplay.
</blockquote></details>

Даже если я вынимаю логику из updateDisplay, то у возникают проблемы с перемещениями между страницами с сохранением шага и слоя. С этими изменениями вроде бы все корректно работает.

**Review by Ivan-okolzin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/31)* status: 0 of 1 approvals obtained, 0 of 10 files reviewed, 7 unresolved discussions (waiting on @ulitiy)

___
*[`src/plugin/tune.ts` line 175 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NRE0GHp4RQDD8XsHA7x:-NRHIbnODDolh_2crhKO:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/b279186b71b051743130b2892be2493e9e050870/src/plugin/tune.ts#L175)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Допиши функцию deleteTmp, устрани дублирование кода
</blockquote></details>

Done.
___
*[`src/plugin/tune.ts` line 201 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NRDyK_3233C7Ws92VhX:-NRHNq136i8v5vj3MXgD:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/b279186b71b051743130b2892be2493e9e050870/src/plugin/tune.ts#L201)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Сделай пожалуйста функцию selectNextStep(criteria: bool). Зачем это прикручивать в updateDisplay?
</blockquote></details>

Done.
___
*[`src/plugin/tune.ts` line 202 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NRDwn5x1JYlMf9gNZgd:-NRHNqDH2tOfSRnlZ7NK:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/b279186b71b051743130b2892be2493e9e050870/src/plugin/tune.ts#L202)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

arr.slice.find
</blockquote></details>

Done.
___
*[`src/plugin/tune.ts` line 205 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NRDxNpOBWuKSOZ0JWN1:-NRHZgPsDSAUkJpRvnkC:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/b279186b71b051743130b2892be2493e9e050870/src/plugin/tune.ts#L205)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

это же PageNode?
</blockquote></details>

Done.
___
*[`src/plugin/tune.ts` line 207 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NRDxc4G6tVs-CG3I42D:-NRHOX4V8UMI7lzSrOoc:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/b279186b71b051743130b2892be2493e9e050870/src/plugin/tune.ts#L207)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

slice
</blockquote></details>

Done.
___
*[`src/plugin/tune.ts` line 209 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NRDy06X1W6nXavOd9ew:-NRHNz8P0uA5TjG2eu2J:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/b279186b71b051743130b2892be2493e9e050870/src/plugin/tune.ts#L209)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

early return
</blockquote></details>

Done.

**Review by ulitiy — CHANGES_REQUESTED** [review]
> Reviewed 6 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/31)* status: 0 of 1 approvals obtained, 6 of 10 files reviewed, 2 unresolved discussions (waiting on @Ivan-okolzin)

___
*[`src/plugin/tune.ts` line 175 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NRE0GHp4RQDD8XsHA7x:-NRJqgC15f3FqBLtza02:b-u7xr8) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/b279186b71b051743130b2892be2493e9e050870/src/plugin/tune.ts#L175)):*
<details><summary><i>Previously, Ivan-okolzin wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Верни обратно. Посмотри на строчку, которую я прокомментировал. Я ожидал deleteTmp(page) вместо deleteTmp(), всё.

**Comment by Ivan-okolzin** [comment]
*[`src/plugin/tune.ts` line 175 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NRE0GHp4RQDD8XsHA7x:-NRbL0fq3Zh2x3aeHvPX:bcvoinj) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/b279186b71b051743130b2892be2493e9e050870/src/plugin/tune.ts#L175)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Верни обратно. Посмотри на строчку, которую я прокомментировал. Я ожидал deleteTmp(page) вместо deleteTmp(), всё.
</blockquote></details>

Дописал функцию deleteTmp, сделал функцию displayAll, чтобы Можно было менять режим отображения предыдущей страницы через updateDisplay.

**Review by ulitiy — COMMENTED** [review]
> Reviewed 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/31)* status: 0 of 1 approvals obtained, 6 of 10 files reviewed, 2 unresolved discussions

*[a discussion](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NRjyTVj7LCMtZEBj-J2:-NRjyTVj7LCMtZEBj-J3:b7e7dpi) (no related file):*
Досмотрю после #32 

___

**Review by ulitiy — COMMENTED** [review]
тут какие новости?

> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-:-NTWexl_A2Q18Sh5UiNa:b-f2huiw)* status: 0 of 1 approvals obtained, 7 of 10 files reviewed, 3 unresolved discussions (waiting on @Ivan-okolzin)

**Review by Ivan-okolzin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/31)* status: 0 of 1 approvals obtained, 7 of 10 files reviewed, 3 unresolved discussions (waiting on @ulitiy)

___
*[`src/plugin/linter.ts` line 465 at r3](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NRk-xOyE_uidSely3RQ:-NTnTNRC6BMruvp3PKPH:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/159d7ba9bef92d4e2071f5a21e12c8f748f00cfa/src/plugin/linter.ts#L465)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

displayAll должен вызывать deleteTmp самостоятельно. Есть ли причина отделять?
</blockquote></details>

Done.
___
*[`src/plugin/tune.ts` line 40 at r3](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NRk0MLcEN0GwI91Ngdp:-NTnALxq7XjFMnuAEaoH:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/159d7ba9bef92d4e2071f5a21e12c8f748f00cfa/src/plugin/tune.ts#L40)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

page вместо lesson упростит точки вызова
</blockquote></details>

Done.
___
*[`src/plugin/tune.ts` line 197 at r3](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NRk3f2iC489Vrhabc_u:-NTnALji7QsFem57vntY:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/159d7ba9bef92d4e2071f5a21e12c8f748f00cfa/src/plugin/tune.ts#L197)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Дублирование кода. Сделай функцию findNextBrushStep(page, stepNumber), будет сносная декомпозиция.
</blockquote></details>

Done.



_Code quote (from src/plugin/linter.ts):_
```XML
    if(lesson) {
      displayAll(lesson, true)
```

**Review by ulitiy — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r2, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/31)* status: 0 of 1 approvals obtained, all files reviewed, 5 unresolved discussions (waiting on @Ivan-okolzin)

___
*[`src/app/components/StepList.tsx` line 35 at r4](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NTvBlF79E6kMEL7Bcya:-NTvBlF79E6kMEL7Bcyb:btaow7n) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/99d8b61d026cfdf278d12c7d2bcd7823caa9c51f/src/app/components/StepList.tsx#L35)):*
> ```XML
>           <ListGroup {...provided.droppableProps} ref={provided.innerRef}>
>             {steps?.map((stepNode, index) => {
>                return stepNode && selectedStep ? (
> ```

Обсуждали уже где-то, это плохое решение.
___
*[`src/plugin/linter.ts` line 465 at r3](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NRk-xOyE_uidSely3RQ:-NTvC9sE1EWqntfrUCBR:b990abb) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/159d7ba9bef92d4e2071f5a21e12c8f748f00cfa/src/plugin/linter.ts#L465)):*
<details><summary><i>Previously, Ivan-okolzin wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Всё равно deleteTmp двумя строчками выше осталось
___
*[`src/plugin/tune.ts` line 40 at r3](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NRk0MLcEN0GwI91Ngdp:-NTvD3op13gru3jVFMe_:bd63cep) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/159d7ba9bef92d4e2071f5a21e12c8f748f00cfa/src/plugin/tune.ts#L40)):*
<details><summary><i>Previously, Ivan-okolzin wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Верни обратно, херня получилась.
___
*[`src/plugin/tune.ts` line 193 at r4](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NTvGJm641kKUILSLuir:-NTvGJm7Ap5BqhGyR5mn:b-m7ukfi) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/99d8b61d026cfdf278d12c7d2bcd7823caa9c51f/src/plugin/tune.ts#L193)):*
> ```XML
> 
> 
>     if (!nextStep) {
> ```

early return
___
*[`src/plugin/tune.ts` line 195 at r4](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NTvFHX15QtEXUifNyel:-NTvFHX25yjaRhz90OQz:b-csnomn) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/99d8b61d026cfdf278d12c7d2bcd7823caa9c51f/src/plugin/tune.ts#L195)):*
> ```XML
>     if (!nextStep) {
>       const lessons = figma.root.children as PageNode[]
>       const nextLesson = lessons.slice(lessons.indexOf(<PageNode>lesson.parent) + 1).find((newLesson) => {
> ```

Чище будет конкретно в этом случае пройтись обычным циклом и сразу же вернуть ответ, когда найдешь результат вместо того чтобы искать сначала урок, содержащий ответ, а потом заново в уроке искать ответ.

Если делать в функциональном стиле, то без лишней вычислительной работы это делается через reduce (складываем сразу окончательный результат в аккумулятор, а в начале проверяем аккумулятор и если он уже занят, то сразу же его возвращаем без какой-то доп. обработки). Если что-то не делается в функциональном стиле через готовые функции, оно скорее всего делается через reduce.

Мне без разницы, в каком стиле сделаешь.
Выйдет значительно короче.

**Comment by Ivan-okolzin** [comment]
*[`src/plugin/linter.ts` line 465 at r3](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NRk-xOyE_uidSely3RQ:-NU1tMuCElL-UvrVZW2i:b-4y8660) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/159d7ba9bef92d4e2071f5a21e12c8f748f00cfa/src/plugin/linter.ts#L465)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Всё равно deleteTmp двумя строчками выше осталось
</blockquote></details>

Он остался наверху, потому что мне нужно удалять tmp  файлы в уроке при переключении на режимы кроме All.

**Comment by Ivan-okolzin** [comment]
*[`src/plugin/tune.ts` line 193 at r4](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NTvGJm641kKUILSLuir:-NU1v0biApquScz2Hy99:b2svfxz) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/99d8b61d026cfdf278d12c7d2bcd7823caa9c51f/src/plugin/tune.ts#L193)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

early return
</blockquote></details>

Там не return. Я в else к этому if присваиваю step = nextStep as GroupNode.

**Comment by Ivan-okolzin** [comment]
Не смотри его. Я еще функцию перепишу одну завтра.

**Review by ulitiy — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r5, 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/31)* status: 0 of 1 approvals obtained, all files reviewed, 2 unresolved discussions (waiting on @Ivan-okolzin)

___
*[`src/plugin/tune.ts` line 193 at r4](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NTvGJm641kKUILSLuir:-NU9tyCY5dLPcjKt3L5N:bzibyt) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/99d8b61d026cfdf278d12c7d2bcd7823caa9c51f/src/plugin/tune.ts#L193)):*
<details><summary><i>Previously, Ivan-okolzin wrote…</i></summary><blockquote>

Там не return. Я в else к этому if присваиваю step = nextStep as GroupNode. 
</blockquote></details>

if nextstep
присвоил selection
return

в чем проблема?
___
*[`src/plugin/tune.ts` line 217 at r6](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NU9vQr23H2ItbtIG9Kw:-NU9vQr23H2ItbtIG9Kx:bhdfj4m) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/cda6eed8ada28d8631ce18f1cba0614828f89635/src/plugin/tune.ts#L217)):*
> ```XML
>       figma.currentPage = nextLesson
>       lesson = findLessonGroup(nextLesson)
>       step = findNextBrushStep(stepsByOrder(lesson)) as GroupNode
> ```

Вот это всё можно положить внутрь редьюса и возвращать в аккумулятор сразу step, тогда ничего искать не придётся повторно.

**Review by Ivan-okolzin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/31)* status: 0 of 1 approvals obtained, all files reviewed, 2 unresolved discussions (waiting on @ulitiy)

___
*[`src/plugin/tune.ts` line 193 at r4](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NTvGJm641kKUILSLuir:-NULPc44Ap0noFKUp7ed:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/99d8b61d026cfdf278d12c7d2bcd7823caa9c51f/src/plugin/tune.ts#L193)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

if nextstep
присвоил selection
return

в чем проблема?
</blockquote></details>

Done.
___
*[`src/plugin/tune.ts` line 217 at r6](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NU9vQr23H2ItbtIG9Kw:-NULbNWg7SZpysKOaqwj:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/cda6eed8ada28d8631ce18f1cba0614828f89635/src/plugin/tune.ts#L217)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Вот это всё можно положить внутрь редьюса и возвращать в аккумулятор сразу step, тогда ничего искать не придётся повторно.
</blockquote></details>

Done.

**Review by ulitiy — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/31)* status: 0 of 1 approvals obtained, all files reviewed, 1 unresolved discussion (waiting on @Ivan-okolzin)

___
*[`src/plugin/tune.ts` line 226 at r7](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NUZhkuFDqVZAyuMP0FK:-NUZhkuFDqVZAyuMP0FL:b-ez0ty1) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/bad1210f0cd42a57a14ce03992db59a67d6f7382/src/plugin/tune.ts#L226)):*
> ```XML
>     lesson = findLessonGroup(page)
>     step = stepsByOrder(lesson)[stepNumber - 1] as GroupNode
>   }
> ```

Если ничего не найдено и мы никуда не переходим, для чего этот код? Без него что-то ломается?

**Review by Ivan-okolzin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/31)* status: 0 of 1 approvals obtained, 9 of 13 files reviewed, 1 unresolved discussion (waiting on @ulitiy)

___
*[`src/plugin/tune.ts` line 226 at r7](https://reviewable.io/reviews/ulitiy/artworkout-figma/31#-NUZhkuFDqVZAyuMP0FK:-NU_ztrLE-Tf_xFyFcKF:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/bad1210f0cd42a57a14ce03992db59a67d6f7382/src/plugin/tune.ts#L226)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Если ничего не найдено и мы никуда не переходим, для чего этот код? Без него что-то ломается?
</blockquote></details>

Done.

**Review by ulitiy — APPROVED** [review]
> Reviewed 12 of 12 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/31)* status: :shipit: complete! 1 of 1 approvals obtained, all files reviewed, all discussions resolved

**Pull request merged**
