### PR TITLE
Add tune checkboxes

### PR DESCRIPTION
**Pull request by Ivan-okolzin**
This change is [Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/23)

### CODE REVIEW

**Review by ulitiy — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/23)* status: 0 of 1 approvals obtained, 8 of 10 files reviewed, 12 unresolved discussions (waiting on @Ivan-okolzin)

___
*[`src/app/components/DisplayForm.tsx` line 42 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/23#-NP00obs9wxf-2JK_BcS:-NP00obt1G6R5GTigPdx:bei30a9) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/2b45de284d65770957f0859f15e5e168312516ad/src/app/components/DisplayForm.tsx#L42)):*
> ```XML
>   const [repeat, setRepeat] = useState<number>(0)
> 
>   const [anotherTags, setAnotherTags] = useState<string[]>([])
> ```

another может относиться только к единственному объекту, anotherTag
Для множественного числа – otherTags
___
*[`src/app/components/DisplayForm.tsx` line 206 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/23#-NP377tODdaBONb5OC0k:-NP377tODdaBONb5OC0l:bl8y5qo) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/2b45de284d65770957f0859f15e5e168312516ad/src/app/components/DisplayForm.tsx#L206)):*
> ```XML
>   const enableOnTags: any = ['INPUT', 'TEXTAREA', 'SELECT']
>   const anotherTagsList: any = [
>     {tag: 'fixed-size', name: 'Fixed size'},
> ```

Не нужен здесь, он ставится однократно на settings
___
*[`src/app/components/DisplayForm.tsx` line 209 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/23#-NP37FIP-WU3_PU4HaPH:-NP37FIP-WU3_PU4HaPI:b-u67beg) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/2b45de284d65770957f0859f15e5e168312516ad/src/app/components/DisplayForm.tsx#L209)):*
> ```XML
>     {tag: 'share-button', name: 'Share button'},
>     {tag:'allow-undo', name: 'Allow undo'},
>     {tag: 'layer', name: 'Layer'},
> ```

А это что за тег? У него иной синтаксис и он вообще теперь выставляется автоматически. Не нужен.
___
*[`src/app/components/DisplayForm.tsx` line 210 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/23#-NP37K1c7i5SkSThg2_z:-NP37K1c7i5SkSThg2a-:b7wdhf3) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/2b45de284d65770957f0859f15e5e168312516ad/src/app/components/DisplayForm.tsx#L210)):*
> ```XML
>     {tag:'allow-undo', name: 'Allow undo'},
>     {tag: 'layer', name: 'Layer'},
>     {tag: 'resize-brush', name: 'Resize brush'},
> ```

Этого тега нет в task.js
___
*[`src/app/components/DisplayForm.tsx` line 244 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/23#-NP3499VEg38Zwyu78er:-NP3499VEg38Zwyu78es:brhqnmm) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/2b45de284d65770957f0859f15e5e168312516ad/src/app/components/DisplayForm.tsx#L244)):*
> ```XML
>         <Form.Group as={Row}>
>           <Form.Label column xs={5}>
>             Step (JK)
> ```

как-то бы ужать по высоте. М.б. тоже на ховер сделать тултип.
___
*[`src/app/components/DisplayForm.tsx` line 258 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/23#-NP35UXlBmT7PMjQ7Z83:-NP35UXmElCpBOGnGYQP:b3tx5bs) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/2b45de284d65770957f0859f15e5e168312516ad/src/app/components/DisplayForm.tsx#L258)):*
> ```XML
>       </Col>
>       <Col>
>         <ButtonToolbar>
> ```

Можно ли их сделать типа radiobutton? В том плане, чтобы визуально было видно текущий режим работы.
___
*[`src/app/components/DisplayForm.tsx` line 286 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/23#-NP36FtfBoy0nE61DyWG:-NP36FtfBoy0nE61DyWH:bp34e0e) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/2b45de284d65770957f0859f15e5e168312516ad/src/app/components/DisplayForm.tsx#L286)):*
> ```XML
>   )
> 
>   const renderDropdownElement = (step, index) => {
> ```

Дропдаун не закрывается на снятие фокуса/клике снаружи.
___
*[`src/app/components/DisplayForm.tsx` line 332 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/23#-NP33xfq-DwrS9HPjrpF:-NP33xfq-DwrS9HPjrpG:b8ssd4z) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/2b45de284d65770957f0859f15e5e168312516ad/src/app/components/DisplayForm.tsx#L332)):*
> ```XML
> 
>   const renderClearLayerDropdown = (
>     <Dropdown className={'mb-2'}  autoClose={false}>
> ```

Можно компактнее?
___
*[`src/app/components/DisplayForm.tsx` line 460 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/23#-NP35zygB4-pIue155Lg:-NP35zygB4-pIue155Lh:b-fvkegw) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/2b45de284d65770957f0859f15e5e168312516ad/src/app/components/DisplayForm.tsx#L460)):*
> ```XML
>       <Row>
>         <Col>
>           <Form.Group as={Row} className={'mb-1'}>
> ```

некрасиво выделяется mb-1
___
*[`src/app/components/DisplayForm.tsx` line 461 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/23#-NP36ubb0DdtnzfeQDH7:-NP36ubc64eLK2QpW4oN:ba181px) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/2b45de284d65770957f0859f15e5e168312516ad/src/app/components/DisplayForm.tsx#L461)):*
> ```XML
>         <Col>
>           <Form.Group as={Row} className={'mb-1'}>
>             <Form.Label column xs={5}>
> ```

предлагаю вообще всю анимацию, clear layer, other tags, delay, repeat убрать под спойлер "advanced"
___
*[`src/app/components/DisplayForm.tsx` line 506 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/23#-NP36UyQDJwrbcIo31V-:-NP36UyQDJwrbcIo31V0:bq913ff) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/2b45de284d65770957f0859f15e5e168312516ad/src/app/components/DisplayForm.tsx#L506)):*
> ```XML
>             </Col>
>           </Form.Group>
>           <Form.Group as={Row} className='mb-2'>
> ```

Это должно идти после brush size
___
*[`src/plugin/tune.ts` line 166 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/23#-NP386LzEGa0rOPf6mz6:-NP386LzEGa0rOPf6mz7:b-6puuat) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/2b45de284d65770957f0859f15e5e168312516ad/src/plugin/tune.ts#L166)):*
> ```XML
>   ).length
>   const maxStrokeWeight = getBrushSize(step)
>   const brushType = getTag(step, 'brush-name-') === '0' ? '' : getTag(step, 'brush-name-')
> ```

что за === '0'? Лучше поменять реализацию метода, сделав ее более универсальной.

**Review by Ivan-okolzin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/23)* status: 0 of 1 approvals obtained, 5 of 10 files reviewed, 12 unresolved discussions (waiting on @ulitiy)

___
*[`src/app/components/DisplayForm.tsx` line 42 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/23#-NP00obs9wxf-2JK_BcS:-NPHNftK3xFBn27CZzd4:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/2b45de284d65770957f0859f15e5e168312516ad/src/app/components/DisplayForm.tsx#L42)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

another может относиться только к единственному объекту, anotherTag
Для множественного числа – otherTags
</blockquote></details>

Done.
___
*[`src/app/components/DisplayForm.tsx` line 206 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/23#-NP377tODdaBONb5OC0k:-NPHNgoHBapzOxrH-cZw:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/2b45de284d65770957f0859f15e5e168312516ad/src/app/components/DisplayForm.tsx#L206)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Не нужен здесь, он ставится однократно на settings
</blockquote></details>

Done.
___
*[`src/app/components/DisplayForm.tsx` line 209 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/23#-NP37FIP-WU3_PU4HaPH:-NPHNic284-dfomVdL42:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/2b45de284d65770957f0859f15e5e168312516ad/src/app/components/DisplayForm.tsx#L209)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

А это что за тег? У него иной синтаксис и он вообще теперь выставляется автоматически. Не нужен.
</blockquote></details>

Done.
___
*[`src/app/components/DisplayForm.tsx` line 210 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/23#-NP37K1c7i5SkSThg2_z:-NPHNjLG1ZdXgMuhNFbE:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/2b45de284d65770957f0859f15e5e168312516ad/src/app/components/DisplayForm.tsx#L210)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Этого тега нет в task.js
</blockquote></details>

Done.
___
*[`src/app/components/DisplayForm.tsx` line 244 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/23#-NP3499VEg38Zwyu78er:-NPH_zHZ4C_l6Pz0tGnQ:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/2b45de284d65770957f0859f15e5e168312516ad/src/app/components/DisplayForm.tsx#L244)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

как-то бы ужать по высоте. М.б. тоже на ховер сделать тултип.
</blockquote></details>

Done.
___
*[`src/app/components/DisplayForm.tsx` line 258 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/23#-NP35UXlBmT7PMjQ7Z83:-NPHa-JM6lUCL9nJZNpo:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/2b45de284d65770957f0859f15e5e168312516ad/src/app/components/DisplayForm.tsx#L258)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Можно ли их сделать типа radiobutton? В том плане, чтобы визуально было видно текущий режим работы.
</blockquote></details>

Done.
___
*[`src/app/components/DisplayForm.tsx` line 286 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/23#-NP36FtfBoy0nE61DyWG:-NPHa2uL11X4H3uG2YDi:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/2b45de284d65770957f0859f15e5e168312516ad/src/app/components/DisplayForm.tsx#L286)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Дропдаун не закрывается на снятие фокуса/клике снаружи.
</blockquote></details>

Done.
___
*[`src/app/components/DisplayForm.tsx` line 332 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/23#-NP33xfq-DwrS9HPjrpF:-NPM1lC365CEevdW-q_3:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/2b45de284d65770957f0859f15e5e168312516ad/src/app/components/DisplayForm.tsx#L332)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Можно компактнее?
</blockquote></details>

Done.
___
*[`src/app/components/DisplayForm.tsx` line 460 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/23#-NP35zygB4-pIue155Lg:-NPHa6Lz4V4Lui7baOMs:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/2b45de284d65770957f0859f15e5e168312516ad/src/app/components/DisplayForm.tsx#L460)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

некрасиво выделяется mb-1
</blockquote></details>

Done.
___
*[`src/app/components/DisplayForm.tsx` line 461 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/23#-NP36ubb0DdtnzfeQDH7:-NPIBTlC-NUhUCsY850e:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/2b45de284d65770957f0859f15e5e168312516ad/src/app/components/DisplayForm.tsx#L461)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

предлагаю вообще всю анимацию, clear layer, other tags, delay, repeat убрать под спойлер "advanced"
</blockquote></details>

Done.
___
*[`src/app/components/DisplayForm.tsx` line 506 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/23#-NP36UyQDJwrbcIo31V-:-NPHaVfn-p81sou71gnr:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/2b45de284d65770957f0859f15e5e168312516ad/src/app/components/DisplayForm.tsx#L506)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

Это должно идти после brush size
</blockquote></details>

Done.
___
*[`src/plugin/tune.ts` line 166 at r1](https://reviewable.io/reviews/ulitiy/artworkout-figma/23#-NP386LzEGa0rOPf6mz6:-NPMAbz_0hrxJ6v-hGsB:b-896fix) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/2b45de284d65770957f0859f15e5e168312516ad/src/plugin/tune.ts#L166)):*
<details><summary><i>Previously, ulitiy (Alexander Ulitin) wrote…</i></summary><blockquote>

что за === '0'? Лучше поменять реализацию метода, сделав ее более универсальной.
</blockquote></details>

Done.

**Review by ulitiy — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/23)* status: 0 of 1 approvals obtained, all files reviewed, 2 unresolved discussions (waiting on @Ivan-okolzin)

*[a discussion](https://reviewable.io/reviews/ulitiy/artworkout-figma/23#-NPPbT8EBhKKsLJrr7xG:-NPPbT8FAVW-5jqTnxnX:b-7lny9p) (no related file):*
При запуске плагина, поля не заполняются.

___
___
*[`src/app/components/DisplayForm.tsx` line 149 at r2](https://reviewable.io/reviews/ulitiy/artworkout-figma/23#-NPPYLDt7BFS0mwiXBjB:-NPPYLDt7BFS0mwiXBjC:bcqnz7g) ([raw file](https://github.com/ulitiy/artworkout-figma/blob/a54ca5aaeaa104c5a9dad388ee575d70bd671f18/src/app/components/DisplayForm.tsx#L149)):*
> ```XML
>         clearLayers,
>         clearBefore,
>         anotherTags: otherTags,
> ```

another tags не должно нигде остаться, заменяй. И another tag тоже.

**Review by ulitiy — APPROVED** [review]
> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ulitiy/artworkout-figma/23)* status: :shipit: complete! 1 of 1 approvals obtained, all files reviewed, all discussions resolved

**Pull request merged**
